server:
  port: ${port:8089}

logging:
  level:
    root: ${loglevel:INFO}
    #DEBUG

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://34.135.239.235:5432/postgresdb}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PWD:test123}
    driver-class-name: ${DATABASE_DRIVERCLASS:org.postgresql.Driver}

topic:
  dispatchertopic: ${DISPATCHERTOPIC:neftil-dispatcher-topic}
  errortopic: ${ERROR_TOPIC:neftil-dispatcher-topic}

